"""
UrbanEye AI — SQLAlchemy Declarative Base and Timestamp Mixin

All ORM models inherit from `Base` and use `TimestampMixin` to get:
  • UUID primary key (auto-generated)
  • created_at  (timezone-aware, set on INSERT)
  • updated_at  (timezone-aware, set on INSERT and UPDATE)

Uses SQLAlchemy's dialect-agnostic ``Uuid`` type so the same models
work with PostgreSQL (production) and SQLite (tests).
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Uuid, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """SQLAlchemy 2.x declarative base shared by all models."""
    pass


class TimestampMixin:
    """
    Mixin that adds UUID primary key and timezone-aware timestamps.

    Attributes:
        id:         UUID primary key, auto-generated by Python.
        created_at: Timestamp of record creation (UTC).
        updated_at: Timestamp of last update (UTC), auto-updated on write.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
