/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BusesRouteImport } from './routes/buses'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as RoadsRouteImport } from './routes/roads'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WorkQueueRouteImport } from './routes/work-queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BusesRoute = BusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsRoute = RoadsRouteImport.update({
  id: '/roads',
  path: '/roads',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkQueueRoute = WorkQueueRouteImport.update({
  id: '/work-queue',
  path: '/work-queue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buses': typeof BusesRoute
  '/executive': typeof ExecutiveRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/overview': typeof OverviewRoute
  '/roads': typeof RoadsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/traffic': typeof TrafficRoute
  '/verification': typeof VerificationRoute
  '/videos': typeof VideosRoute
  '/work-queue': typeof WorkQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buses': typeof BusesRoute
  '/executive': typeof ExecutiveRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/overview': typeof OverviewRoute
  '/roads': typeof RoadsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/traffic': typeof TrafficRoute
  '/verification': typeof VerificationRoute
  '/videos': typeof VideosRoute
  '/work-queue': typeof WorkQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buses': typeof BusesRoute
  '/executive': typeof ExecutiveRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/overview': typeof OverviewRoute
  '/roads': typeof RoadsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/traffic': typeof TrafficRoute
  '/verification': typeof VerificationRoute
  '/videos': typeof VideosRoute
  '/work-queue': typeof WorkQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/buses'
    | '/executive'
    | '/fleet'
    | '/incidents'
    | '/login'
    | '/map'
    | '/overview'
    | '/roads'
    | '/safety'
    | '/settings'
    | '/traffic'
    | '/verification'
    | '/videos'
    | '/work-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/buses'
    | '/executive'
    | '/fleet'
    | '/incidents'
    | '/login'
    | '/map'
    | '/overview'
    | '/roads'
    | '/safety'
    | '/settings'
    | '/traffic'
    | '/verification'
    | '/videos'
    | '/work-queue'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/buses'
    | '/executive'
    | '/fleet'
    | '/incidents'
    | '/login'
    | '/map'
    | '/overview'
    | '/roads'
    | '/safety'
    | '/settings'
    | '/traffic'
    | '/verification'
    | '/videos'
    | '/work-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BusesRoute: typeof BusesRoute
  ExecutiveRoute: typeof ExecutiveRoute
  FleetRoute: typeof FleetRoute
  IncidentsRoute: typeof IncidentsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  OverviewRoute: typeof OverviewRoute
  RoadsRoute: typeof RoadsRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  TrafficRoute: typeof TrafficRoute
  VerificationRoute: typeof VerificationRoute
  VideosRoute: typeof VideosRoute
  WorkQueueRoute: typeof WorkQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buses': {
      id: '/buses'
      path: '/buses'
      fullPath: '/buses'
      preLoaderRoute: typeof BusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads': {
      id: '/roads'
      path: '/roads'
      fullPath: '/roads'
      preLoaderRoute: typeof RoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-queue': {
      id: '/work-queue'
      path: '/work-queue'
      fullPath: '/work-queue'
      preLoaderRoute: typeof WorkQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BusesRoute: BusesRoute,
  ExecutiveRoute: ExecutiveRoute,
  FleetRoute: FleetRoute,
  IncidentsRoute: IncidentsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  OverviewRoute: OverviewRoute,
  RoadsRoute: RoadsRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  TrafficRoute: TrafficRoute,
  VerificationRoute: VerificationRoute,
  VideosRoute: VideosRoute,
  WorkQueueRoute: WorkQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
